####################################################################
## %%USERNAME%% will be replaced by actual username ##
####################################################################
[ req ]
distinguished_name    = req_distinguished_name

string_mask           = nombstr

# The extensions to add to a certificate request
req_extensions        = v3_req

# GWDG default options for certificate request
[ req_distinguished_name ]
countryName                = Country Name (2 letter code)
countryName_default        = DE
countryName_min            = 2
countryName_max            = 2

stateOrProvinceName            = State or Province Name (full name)
stateOrProvinceName_default    = Berlin

localityName                = Your City
localityName_default        = Berlin

0.organizationName            = Organization Name (eg, company)
0.organizationName_default    = TUB

# Dieser Teil ist Optional und kann bei Bedarf einkommentiert werden
# Wichtig: Es dürfen keine Sonderzeichen wie z.B. auch ein - oder _ dort vorkommen!
#
# organizationalUnitName            = Organizational Unit Name (eg, section)
# organizationalUnitName_default    =  AG A

commonName              = %%USERNAME%%@localhost
commonName_max          = 64
commonName_default      = localhost
 
[ v3_req ]
basicConstraints        = CA:FALSE
subjectKeyIdentifier    = hash
#authorityKeyIdentifier  = keyid,issuer
#keyUsage                = critical, nonRepudiation, digitalSignature, keyEncipherment
#extendedKeyUsage        = clientAuth
subjectAltName          = URI:urn:publicid:IDN+localhost+user+%%USERNAME%%

####################################################################
