#!/bin/bash
#
# fiteagled        Startup script for the FITeagle Federation Server
#
# chkconfig: - 85 15
# description: The FITeagle Federation Server is an efficient and extensible  \
#              server implementing the current Federation standards.
# processname: fiteagled
# config: /etc/fiteagled/conf/fiteagled.conf
# config: /etc/sysconfig/fiteagled
# pidfile: /var/run/fiteagled.pid
#
### BEGIN INIT INFO
# Provides: fiteagled
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6
# Should-Start: 
# Short-Description: start and stop FITeagle Federation Server
# Description: The FITeagle Federation Server is an extensible server 
#  implementing the current Federation standards.
### END INIT INFO

# Source function library.
#. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/fiteagled ]; then
        . /etc/sysconfig/fiteagled
fi

source /etc/profile

# Path to the fiteagle.sh script, server binary, and short-form for messages.
fiteagleuser=${FITEAGLEUSER-fiteagle}
fiteaglepath=${FITEAGLEPATH-/home/$fiteagleuser/bootstrap}
fiteagle=${FITEAGLE-$fiteaglepath/fiteagle.sh}
prog=fiteagle
pidfile=${PIDFILE-/var/run/fiteagled.pid}
lockfile=${LOCKFILE-/var/lock/fiteagled}
logfile=${LOGFILE-/var/log/fiteagled}
RETVAL=0
PATH=$PATH:/usr/local/sbin
args_j2ee=startJ2EE

xmpp_root=${OPENFIRE_HOME-$fiteaglepath/../server/openfire}
prog_xmpp=fiteagle_xmpp
pidfile_xmpp=${PIDFILE_XMPP-/var/run/fiteagle_xmpp.pid}
lockfile_xmpp=${LOCKFILE_XMPP-/var/lock/fiteagle_xmpp}
logfile_xmpp=${LOGFILE_XMPP-/var/log/fiteagle_xmpp}
args_xmpp=startXMPP

touch $logfile
touch $logfile_xmpp
chown $fiteagleuser $logfile
chown $fiteagleuser $logfile_xmpp
chown -R $fiteagleuser $xmpp_root

start() {
        echo -n $"Starting $prog.. "
        start-stop-daemon --start --background --chuid $fiteagleuser --pidfile $pidfile --make-pidfile --name $prog --exec /bin/bash -- -c "$fiteagle $args_j2ee > $logfile 2>&1"
        RETVAL=$?
        [ $RETVAL = 0 ] && touch ${lockfile}
        echo $"OK. Check logs at $logfile."
        echo -n $"Starting $prog_xmpp.. "
        start-stop-daemon --start --background --chuid $fiteagleuser --pidfile $pidfile_xmpp --make-pidfile --name $prog_xmpp --exec /bin/bash -- -c "$fiteagle $args_xmpp > $logfile_xmpp 2>&1"
        RETVAL=$?
        [ $RETVAL = 0 ] && touch ${lockfile_xmpp}
        echo $"OK. Check logs at $logfile_xmpp."
        return $RETVAL
}
stop() {
        echo -n $"Stopping $prog.. "
        $fiteagle stopJ2EE
        pid=$(cat $pidfile)
        [ ! -z $pid ] && pkill -P $pid
        echo -n $"Stopping $prog_xmpp.. "
        $fiteagle stopXMPP
        pid=$(cat $pidfile_xmpp)
        [ ! -z $pid ] && pkill -P $pid
        rm -f ${lockfile} ${pidfile}
        rm -f ${lockfile_xmpp} ${pidfile_xmpp}
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2
        start
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart}"
        RETVAL=2
esac

exit $RETVAL
