#!/bin/bash
#
# fiteagled        Startup script for the FITeagle Federation Server
#
# chkconfig: - 85 15
# description: The FITeagle Federation Server is an efficient and extensible  \
#              server implementing the current Federation standards.
# processname: fiteagled
# config: /etc/fiteagled/conf/fiteagled.conf
# config: /etc/sysconfig/fiteagled
# pidfile: /var/run/fiteagled.pid
#
### BEGIN INIT INFO
# Provides: fiteagled
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6
# Should-Start: 
# Short-Description: start and stop FITeagle Federation Server
# Description: The FITeagle Federation Server is an extensible server 
#  implementing the current Federation standards.
### END INIT INFO

# Source function library.
#. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/fiteagled ]; then
        . /etc/sysconfig/fiteagled
fi

source /etc/profile

# Path to the fiteagle.sh script, server binaries, and short-form for messages.
fiteagleuser=${FITEAGLEUSER-fiteagle}
fiteaglepath=${FITEAGLEPATH-/home/$fiteagleuser/bootstrap}
fiteagle=${FITEAGLE-$fiteaglepath/fiteagle.sh}

prog_j2ee=fiteagle_j2ee
pidfile_j2ee=${PIDFILE-/var/run/fiteagle_j2ee.pid}
lockfile_j2ee=${LOCKFILE-/var/lock/fiteagle_j2ee}
logfile_j2ee=${LOGFILE-/var/log/fiteagle_j2ee}
args_j2ee=startJ2EE

xmpp_root=${OPENFIRE_HOME-$fiteaglepath/../server/openfire}
prog_xmpp=fiteagle_xmpp
pidfile_xmpp=${PIDFILE_XMPP-/var/run/fiteagle_xmpp.pid}
lockfile_xmpp=${LOCKFILE_XMPP-/var/lock/fiteagle_xmpp}
logfile_xmpp=${LOGFILE_XMPP-/var/log/fiteagle_xmpp}
args_xmpp=startXMPP

#sparql_root=${SPARQL_HOME-$fiteaglepath/../server/}
prog_sparql=fiteagle_sparql
pidfile_sparql=${PIDFILE_SPARQL-/var/run/fiteagle_sparql.pid}
lockfile_sparql=${LOCKFILE_SPARQL-/var/lock/fiteagle_sparql}
logfile_sparql=${LOGFILE_SPARQL-/var/log/fiteagle_sparql}
args_sparql=startSPARQL

touch $logfile_j2ee
touch $logfile_xmpp
chown $fiteagleuser $logfile_j2ee
chown $fiteagleuser $logfile_xmpp
chown -R $fiteagleuser $xmpp_root
#chown -R $fiteagleuser $sparql_root

RETVAL=0
PATH=$PATH:/usr/local/sbin

start() {
        echo -n $"Starting $prog_j2ee.. "
        start-stop-daemon --start --background --chuid $fiteagleuser --pidfile $pidfile_j2ee --make-pidfile --name $prog_j2ee --exec /bin/bash -- -c "$fiteagle $args_j2ee > $logfile_j2ee 2>&1"
        RETVAL=$?
        [ $RETVAL = 0 ] && touch ${lockfile_j2ee}
        echo $"OK. Check logs at $logfile_j2ee."

        echo -n $"Starting $prog_xmpp.. "
        start-stop-daemon --start --background --chuid $fiteagleuser --pidfile $pidfile_xmpp --make-pidfile --name $prog_xmpp --exec /bin/bash -- -c "$fiteagle $args_xmpp > $logfile_xmpp 2>&1"
        RETVAL=$?
        [ $RETVAL = 0 ] && touch ${lockfile_xmpp}
        echo $"OK. Check logs at $logfile_xmpp."
        
        echo -n $"Starting $prog_sparql.. "
        start-stop-daemon --start --background --chuid $fiteagleuser --pidfile $pidfile_sparql --make-pidfile --name $prog_sparql --exec /bin/bash -- -c "$fiteagle $args_sparql > $logfile_sparql 2>&1"
        sh ./fuseki-server -config "${_sparql_config}"

        return $RETVAL
}
stop() {
        echo -n $"Stopping $prog_j2ee.. "
        $fiteagle stopJ2EE
        pid=$(cat $pidfile_j2ee)
        [ ! -z $pid ] && pkill -P $pid

        echo -n $"Stopping $prog_xmpp.. "
        $fiteagle stopXMPP
        pid=$(cat $pidfile_xmpp)
        [ ! -z $pid ] && pkill -P $pid

        echo -n $"Stopping $prog_sparql.. "
       # $fiteagle stopSPARQL
        pid=$(cat $pidfile_sparql)
        [ ! -z $pid ] && pkill -P $pid

        rm -f ${lockfile_sparql} ${pidfile_sparql}
        rm -f ${lockfile_j2ee} ${pidfile_j2ee}
        rm -f ${lockfile_xmpp} ${pidfile_xmpp}
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2
        start
        ;;
  *)
        echo $"Usage: fiteagled {start|stop|restart}"
        RETVAL=2
esac

exit $RETVAL
